apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "dist-mnist-for-e2e-test"
spec:
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
            steamer-service-type: system
        spec:
          containers:
            - name: tensorflow
              image: harbor.tidu.cd/qujun/training/tf-dist-mnist-test:1.0
              imagePullPolicy: Always
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
            steamer-service-type: system
        spec:
          containers:
            - name: tensorflow
              image: harbor.tidu.cd/qujun/training/tf-dist-mnist-test:1.0
              imagePullPolicy: Always
